### PR TITLE
Request to add Base Event Stack realization

### LINKED ISSUE #12: Base event stack
Event stack is a event list, from which events are taken, in event put our ship, trades, enemies, locations etc.

Event stack should include:
- [ ] Battle event
    * Battles in differents locations
    * Battles with pirates of fetishists
    * Random Battles
- [ ] Trade event
    * Trade with different traders
    * Traders in special locations (sometimes randomly)

### PR DESCRIPTION
**Pull request by ViRGiL175**
Base `EventStack` realization with `getEvent()` method. Using comments included.

Base event stack realisation  …			7730c78

Resolve #12

### CODE REVIEW

**Comment by ViRGiL175** [comment]
Branch rebased atop of `dev`.

**Comment by ViRGiL175** [comment]
Rebased atop.

**Review by ghost — APPROVED** [review]
Approved

**Comment by ghost** [comment]
Reviewed

**Comment by ViRGiL175** [comment]
Rebased atop.

**Pull request merged**
